FROM node:latest

WORKDIR /workspaces/Codefolio/frontend

ARG CODESPACE_NAME
  
ENV CODESPACE_NAME=${CODESPACE_NAME}

COPY ./frontend/package*.json .

RUN npm install -g serve

RUN npm install

COPY ./frontend .

EXPOSE 3000

#RUN npm run build

RUN VITE_CODESPACE_NAME=${CODESPACE_NAME} npm run build

#CMD ["sh", "-c", "echo Environment VITE_CODESPACE_NAME is $VITE_CODESPACE_NAME && serve -s dist"]
CMD ["serve", "-s", "dist"]
#CMD ["npm", "run", "dev"]
