version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
      args:
        CODESPACE_NAME: "${CODESPACE_NAME}"
    #entrypoint: ["/post_start_script.sh"] # Correct location for entrypoint
    volumes:
      - frontend-data:/app  # Mount named volume to /app directory in frontend container
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - VITE_CODESPACE_NAME="${CODESPACE_NAME}"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
      args:
        CODESPACE_NAME: "${CODESPACE_NAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    volumes:
      - backend-data:/app  # Mount named volume to /app directory in backend container
    ports:
      - '8000:8000'
    environment:
      - BACKEND_URL=http://localhost

volumes:
  frontend-data:  # Define the frontend-data named volume
  backend-data:   # Define the backend-data named volume
