version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
      args:
        CODESPACE_NAME: ${CODESPACE_NAME}
    volumes:
      - ../..:/workspaces:cached
    ports:
      - '3000:3000'
    environment:
      - VITE_CODESPACE_NAME="${CODESPACE_NAME}"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
      args:
        CODESPACE_NAME: "${CODESPACE_NAME}"
        GITHUB_USER: "${GITHUB_USER}"
    volumes:
      - ../..:/workspaces:cached
    ports:
      - '8000:8000'
    depends_on:
      - app

volumes:
  frontend-data:
  backend-data:

networks:
  default:
    driver: bridge
