version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
      args:
        CODESPACE_NAME: ${CODESPACE_NAME}
    ports:
      - '3000:3000'
    environment:
      - VITE_CODESPACE_NAME="${CODESPACE_NAME}"
    restart: on-failure
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
      args:
        CODESPACE_NAME: "${CODESPACE_NAME}"
    environment:
      CODESPACE_NAME: "${CODESPACE_NAME}"
    restart: on-failure
    ports:
      - '8000:8000'
    depends_on:
      - app

volumes:
  frontend-data:
  backend-data:

networks:
  default:
    driver: bridge
