FROM python

WORKDIR /backend

COPY ./backend/requirements.txt ./

RUN pip install --upgrade pip

RUN pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt

COPY ./backend .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
