name: Release Please

on:
  push:
    branches:
      - main
      - develop
      - pre_release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please for pre_release branch
        if: github.ref == 'refs/heads/pre_release'
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'simple'
          target-branch: 'pre_release'
          pre-release: true 
      
      - name: Release Please for main and develop branches
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'simple'
          target-branch: ${{ github.ref_name }}

